carts/urls.py
from django.urls import path

from . import views

app_name = "carts"
urlpatterns = [
    path("", views.ListView.as_view(), name="list"),
    path("savecart/", views.SaveCartView.as_view(), name="save"),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
]

mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from users import views as user_views
from carts import views as cart_views

urlpatterns = [
    path("products/", include("products.urls")),
    path("register/", user_views.register, name="register"),
    path("login/", auth_views.LoginView.as_view(
        template_name='users/login.html'), name="login"),
    path("logout/", user_views.UserLogoutView.as_view(
        http_method_names=['get', 'post', 'options']), name="logout"),
    path("profile/", user_views.profile, name="profile"),
    path("cart/", include("carts.urls")),
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from . import views

app_name = "products"
urlpatterns = [
    path("", views.ListView.as_view(), name="list"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    # path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    # path("<int:question_id>/vote/", views.vote, name="vote"),
]

carts/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product

# Create your models here.


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Cart for {self.user.username}"


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name='items',
                             on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        unique_together = ["cart", "product"]

    def save(self, *args, **kwargs):
        self.total_price = self.product.price * self.quantity
        super(CartItem, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.quantity} x {self.product.name} in cart for {self.cart.user.username}"

products/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(default='default.jpg',
                              upload_to='product_images/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Inventory(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.product.name} {self.quantity}"

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

carts/views.py
import json
from django.shortcuts import get_object_or_404, redirect, render
from django.views import generic, View
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.urls import reverse_lazy

from .models import Cart, CartItem
from products.models import Product
from .serializers import CartItemSerializer, CartSerializer


class ListView(generic.ListView):
    model = Cart
    template_name = 'carts/cart_list.html'
    context_object_name = 'cart_list'

    def get_queryset(self):
        # Filter the queryset to get the cart for the current user
        # return get_object_or_404(Cart, user=self.request.user)

        try:
            cart = Cart.objects.filter(user=self.request.user)
            return cart[0]
        except TypeError:
            return Cart.objects.none()


class SaveCartView(View):
    def post(self, request):
        print("save cart view..", request.POST)
        if not request.user.is_authenticated:
            return HttpResponse(json.dumps({"result": "redirect", "status": 302}))

        cart = json.loads(request.POST.get("cart"))
        for item_id, cart_item in cart.items():
            print(cart_item)
            data = {
                "product": item_id,
                "quantity": cart_item.get("count"),
            }
            s = CartItemSerializer(data=data,
                                   context={"request": request})
            if s.is_valid():
                s.save()
            else:
                print(s.errors)

        return HttpResponse(json.dumps({"result": "save cart successful", "status": 201}))


class CheckoutView(View):
    template_name = "carts/checkout.html"

    def get(self, request):
        return render(request, self.template_name)

products/views.py
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Product

# Create your views here.


class ListView(generic.ListView):
    # model = Product
    queryset = Product.objects.select_related("user")


class DetailView(generic.DetailView):
    model = Product

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from .forms import UserRegisterForm
from django.contrib import messages

# Create your views here.


# https://youtu.be/q4jPR-M0TAQ?si=I9fg_LdpEZnnxFLS&t=1644
def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request,
                "Your Account has been created! You are now able to login.")
            return redirect("login")
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


class UserLogoutView(LogoutView):

    def get(self, request):
        logout(request)
        return redirect('login')


@login_required
def profile(request):
    return render(request, 'users/profile.html')

carts/templates/carts/cart_list.html
{% extends "products/base.html" %}
{% load static %}
{% block content %}
  <div class="untree_co-section before-footer-section">
    <div class="container">
      <div class="row mb-5">
        <form class="col-md-12" method="post">
          <div class="site-blocks-table">
            <table class="table" id="cartTable">
              <thead>
                <tr>
                  <th class="product-name">Product</th>
                  <th class="product-price">Price</th>
                  <th class="product-quantity">Quantity</th>
                  <th class="product-total">Total</th>
                  <th class="product-remove">Remove</th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>
        </form>
      </div>

      <div class="row">
        <div class="col-md-6">
          <div class="row mb-5">
            <div class="col-md-6 mb-3 mb-md-0">
              <button class="btn btn-black btn-sm btn-block" id="save-cart">Save Cart</button>
            </div>
            <div class="col-md-6">
              <button class="btn btn-outline-black btn-sm btn-block">Continue Shopping</button>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <label class="text-black h4" for="coupon">Coupon</label>
              <p>Enter your coupon code if you have one.</p>
            </div>
            <div class="col-md-8 mb-3 mb-md-0">
              <input type="text" class="form-control py-3" id="coupon" placeholder="Coupon Code">
            </div>
            <div class="col-md-4">
              <button class="btn btn-black">Apply Coupon</button>
            </div>
          </div>
        </div>
        <div class="col-md-6 pl-5">
          <div class="row justify-content-end">
            <div class="col-md-7">
              <div class="row">
                <div class="col-md-12 text-right border-bottom mb-5">
                  <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                </div>
              </div>
              <div class="row mb-3">
                <div class="col-md-6">
                  <span class="text-black">Subtotal</span>
                </div>
                <div class="col-md-6 text-right">
                  <strong class="text-black">$<span id="cartSubTotal">0</span></strong>
                </div>
              </div>
              <div class="row mb-5">
                <div class="col-md-6">
                  <span class="text-black">Total</span>
                </div>
                <div class="col-md-6 text-right">
                  <strong class="text-black">$<span id="cartTotal">0</span></strong>
                </div>
              </div>

              <div class="row">
                <div class="col-md-12">
                  <button class="btn btn-black btn-lg py-3 btn-block" onclick="window.location='{% url 'carts:checkout' %}'">Proceed To Checkout</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block scripts %}
  {{ block.super }}
  <script type="text/javascript">
    console.log("hello world")
    $(document).ready(function() {
      "use strict";
      console.log("cart list page")
      displayCartTable();

      $("#cartTable tbody").on("click", ".plus-item", function(event) {
        event.preventDefault()
        console.log("clicked plus-item")
        const itemId = $(this).data("id");
        shoppingCart.updateItemCount(itemId, 1);
        displayCartTable()
      });

      $("#cartTable tbody").on("click", ".subtract-item", function(event) {
        event.preventDefault();
        console.log("clicked subtract-item")
        const itemId = $(this).data("id");
        shoppingCart.updateItemCount(itemId, -1);
        displayCartTable()
      });

      $("#cartTable tbody").on("click", ".remove-product", function(event) {
        event.preventDefault();
        const itemId = $(this).data("id");
        shoppingCart.removeProductFromCart(itemId);
        displayCartTable()
      });
        $("#save-cart").click(function() {
            const cartItems = shoppingCart.listItemInCart();
            console.log("-------", typeof cartItems);
            console.log(cartItems);
            $.ajax({
                type: "POST",
                url: "{% url 'carts:save' %}",
                dataType: "json",
                headers: {
                    "X-CSRFToken": "{{ csrf_token }}",
                },
                data: {
                    cart: JSON.stringify(cartItems),
                },
                success: function(data, status, settings) {
                    console.log("ajax POST success");
                    console.log(data, status, settings);
                    if (data["status"] === 302) {
                        window.location.href = "{% url 'login' %}?next=" 
                            + encodeURIComponent("{% url 'carts:list' %}");
                    }
                },
                error: function(xhr, errmsg, err) {
                    console.log("Error:", xhr.status + ": " + xhr.responseText);
                    console.log(errmsg)
                }
            });
        });
    });

    function displayCartTable() {
      const cartItems = shoppingCart.listItemInCart();
      let output = "";
      for (let i in cartItems) {
        const item = cartItems[i];
        const itemTotalCost = shoppingCart.getItemTotalCost(i);
        console.log(item);
        output += '<tr>';
        output += '<td class="product-name"><h2 class="h5 text-black">' + item.name + '</h2></td>';
        output += '<td class="itemPrice">' + item.price + '</td>';
        output += '<td><div class="input-group mb-3 d-flex align-items-center quantity-container" style="max-width: 120px;">';
        output += '<div class="input-group-prepend subtract-item" data-id=' + item.id + '>';
        output += '<button class="btn btn-outline-black decrease" type="button">&minus;</button>'
        output += '</div><input type="text" class="form-control text-center quantity-amount" value="' + item.count;
        output += '" placeholder="" aria-label="button with label" aria-describedby="button-addon1">';
        output += '<div class="input-group-append plus-item" data-id=' + item.id + '>';
        output += '<button class="btn btn-outline-black increase" type="button">&plus;</button></div></div></td>';
        output += '<td class="itemTotal">' + itemTotalCost + '</td>';
        output += '<td class="remove-product" data-id=' + item.id +'><a href="#" class="btn btn-black btn-sm">X</a></td></tr>';
      }
      $("#cartTable tbody").html(output);

      $("#cartTotal").text(shoppingCart.getTotalCartCost())
      $("#cartSubTotal").text(shoppingCart.getTotalCartCost())

      console.log("triggering new event ", shoppingCart.getCartCount())
      $(document).trigger('UpdateTotalCountEvent', shoppingCart.getCartCount())

    }
	</script> 
{% endblock scripts %}

carts/templates/carts/checkout.html
{% extends "products/base.html" %}
{% load static %}
{% block content %}
	<div class="untree_co-section">
		<div class="container">
			<div class="row mb-5">
			<div class="col-md-12">
				<div class="border p-4 rounded" role="alert">
				Returning customer? <a href="#">Click here</a> to login
				</div>
			</div>
			</div>
			<div class="row">
			<div class="col-md-6 mb-5 mb-md-0">
				<h2 class="h3 mb-3 text-black">Billing Details</h2>
				<div class="p-3 p-lg-5 border bg-white">
				<div class="form-group">
					<label for="c_country" class="text-black">Country <span class="text-danger">*</span></label>
					<select id="c_country" class="form-control">
					<option value="1">Select a country</option>    
					<option value="2">bangladesh</option>    
					<option value="3">Algeria</option>    
					<option value="4">Afghanistan</option>    
					<option value="5">Ghana</option>    
					<option value="6">Albania</option>    
					<option value="7">Bahrain</option>    
					<option value="8">Colombia</option>    
					<option value="9">Dominican Republic</option>    
					</select>
				</div>
				<div class="form-group row">
					<div class="col-md-6">
					<label for="c_fname" class="text-black">First Name <span class="text-danger">*</span></label>
					<input type="text" class="form-control" id="c_fname" name="c_fname">
					</div>
					<div class="col-md-6">
					<label for="c_lname" class="text-black">Last Name <span class="text-danger">*</span></label>
					<input type="text" class="form-control" id="c_lname" name="c_lname">
					</div>
				</div>

				<div class="form-group row">
					<div class="col-md-12">
					<label for="c_companyname" class="text-black">Company Name </label>
					<input type="text" class="form-control" id="c_companyname" name="c_companyname">
					</div>
				</div>

				<div class="form-group row">
					<div class="col-md-12">
					<label for="c_address" class="text-black">Address <span class="text-danger">*</span></label>
					<input type="text" class="form-control" id="c_address" name="c_address" placeholder="Street address">
					</div>
				</div>

				<div class="form-group mt-3">
					<input type="text" class="form-control" placeholder="Apartment, suite, unit etc. (optional)">
				</div>

				<div class="form-group row">
					<div class="col-md-6">
					<label for="c_state_country" class="text-black">State / Country <span class="text-danger">*</span></label>
					<input type="text" class="form-control" id="c_state_country" name="c_state_country">
					</div>
					<div class="col-md-6">
					<label for="c_postal_zip" class="text-black">Posta / Zip <span class="text-danger">*</span></label>
					<input type="text" class="form-control" id="c_postal_zip" name="c_postal_zip">
					</div>
				</div>

				<div class="form-group row mb-5">
					<div class="col-md-6">
					<label for="c_email_address" class="text-black">Email Address <span class="text-danger">*</span></label>
					<input type="text" class="form-control" id="c_email_address" name="c_email_address">
					</div>
					<div class="col-md-6">
					<label for="c_phone" class="text-black">Phone <span class="text-danger">*</span></label>
					<input type="text" class="form-control" id="c_phone" name="c_phone" placeholder="Phone Number">
					</div>
				</div>

				<div class="form-group">
					<label for="c_create_account" class="text-black" data-bs-toggle="collapse" href="#create_an_account" role="button" aria-expanded="false" aria-controls="create_an_account"><input type="checkbox" value="1" id="c_create_account"> Create an account?</label>
					<div class="collapse" id="create_an_account">
					<div class="py-2 mb-4">
						<p class="mb-3">Create an account by entering the information below. If you are a returning customer please login at the top of the page.</p>
						<div class="form-group">
						<label for="c_account_password" class="text-black">Account Password</label>
						<input type="email" class="form-control" id="c_account_password" name="c_account_password" placeholder="">
						</div>
					</div>
					</div>
				</div>


				<div class="form-group">
					<label for="c_ship_different_address" class="text-black" data-bs-toggle="collapse" href="#ship_different_address" role="button" aria-expanded="false" aria-controls="ship_different_address"><input type="checkbox" value="1" id="c_ship_different_address"> Ship To A Different Address?</label>
					<div class="collapse" id="ship_different_address">
					<div class="py-2">

						<div class="form-group">
						<label for="c_diff_country" class="text-black">Country <span class="text-danger">*</span></label>
						<select id="c_diff_country" class="form-control">
							<option value="1">Select a country</option>    
							<option value="2">bangladesh</option>    
							<option value="3">Algeria</option>    
							<option value="4">Afghanistan</option>    
							<option value="5">Ghana</option>    
							<option value="6">Albania</option>    
							<option value="7">Bahrain</option>    
							<option value="8">Colombia</option>    
							<option value="9">Dominican Republic</option>    
						</select>
						</div>


						<div class="form-group row">
						<div class="col-md-6">
							<label for="c_diff_fname" class="text-black">First Name <span class="text-danger">*</span></label>
							<input type="text" class="form-control" id="c_diff_fname" name="c_diff_fname">
						</div>
						<div class="col-md-6">
							<label for="c_diff_lname" class="text-black">Last Name <span class="text-danger">*</span></label>
							<input type="text" class="form-control" id="c_diff_lname" name="c_diff_lname">
						</div>
						</div>

						<div class="form-group row">
						<div class="col-md-12">
							<label for="c_diff_companyname" class="text-black">Company Name </label>
							<input type="text" class="form-control" id="c_diff_companyname" name="c_diff_companyname">
						</div>
						</div>

						<div class="form-group row  mb-3">
						<div class="col-md-12">
							<label for="c_diff_address" class="text-black">Address <span class="text-danger">*</span></label>
							<input type="text" class="form-control" id="c_diff_address" name="c_diff_address" placeholder="Street address">
						</div>
						</div>

						<div class="form-group">
						<input type="text" class="form-control" placeholder="Apartment, suite, unit etc. (optional)">
						</div>

						<div class="form-group row">
						<div class="col-md-6">
							<label for="c_diff_state_country" class="text-black">State / Country <span class="text-danger">*</span></label>
							<input type="text" class="form-control" id="c_diff_state_country" name="c_diff_state_country">
						</div>
						<div class="col-md-6">
							<label for="c_diff_postal_zip" class="text-black">Posta / Zip <span class="text-danger">*</span></label>
							<input type="text" class="form-control" id="c_diff_postal_zip" name="c_diff_postal_zip">
						</div>
						</div>

						<div class="form-group row mb-5">
						<div class="col-md-6">
							<label for="c_diff_email_address" class="text-black">Email Address <span class="text-danger">*</span></label>
							<input type="text" class="form-control" id="c_diff_email_address" name="c_diff_email_address">
						</div>
						<div class="col-md-6">
							<label for="c_diff_phone" class="text-black">Phone <span class="text-danger">*</span></label>
							<input type="text" class="form-control" id="c_diff_phone" name="c_diff_phone" placeholder="Phone Number">
						</div>
						</div>

					</div>

					</div>
				</div>

				<div class="form-group">
					<label for="c_order_notes" class="text-black">Order Notes</label>
					<textarea name="c_order_notes" id="c_order_notes" cols="30" rows="5" class="form-control" placeholder="Write your notes here..."></textarea>
				</div>

				</div>
			</div>
			<div class="col-md-6">

				<div class="row mb-5">
				<div class="col-md-12">
					<h2 class="h3 mb-3 text-black">Coupon Code</h2>
					<div class="p-3 p-lg-5 border bg-white">

					<label for="c_code" class="text-black mb-3">Enter your coupon code if you have one</label>
					<div class="input-group w-75 couponcode-wrap">
						<input type="text" class="form-control me-2" id="c_code" placeholder="Coupon Code" aria-label="Coupon Code" aria-describedby="button-addon2">
						<div class="input-group-append">
						<button class="btn btn-black btn-sm" type="button" id="button-addon2">Apply</button>
						</div>
					</div>

					</div>
				</div>
				</div>

				<div class="row mb-5">
				<div class="col-md-12">
					<h2 class="h3 mb-3 text-black">Your Order</h2>
					<div class="p-3 p-lg-5 border bg-white">
					<table class="table site-block-order-table mb-5" id="orderTable">
						<thead>
						<th>Product</th>
						<th>Total</th>
						</thead>
						<tbody>
						<tr>
							<td>Top Up T-Shirt <strong class="mx-2">x</strong> 1</td>
							<td>$250.00</td>
						</tr>
						<tr>
							<td>Polo Shirt <strong class="mx-2">x</strong>   1</td>
							<td>$100.00</td>
						</tr>
						<tr>
							<td class="text-black font-weight-bold"><strong>Cart Subtotal</strong></td>
							<td class="text-black">$350.00</td>
						</tr>
						<tr>
							<td class="text-black font-weight-bold"><strong>Order Total</strong></td>
							<td class="text-black font-weight-bold"><strong>$350.00</strong></td>
						</tr>
						</tbody>
					</table>

					<div class="border p-3 mb-3">
						<h3 class="h6 mb-0"><a class="d-block" data-bs-toggle="collapse" href="#collapsebank" role="button" aria-expanded="false" aria-controls="collapsebank">Direct Bank Transfer</a></h3>

						<div class="collapse" id="collapsebank">
						<div class="py-2">
							<p class="mb-0">Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order won’t be shipped until the funds have cleared in our account.</p>
						</div>
						</div>
					</div>

					<div class="border p-3 mb-3">
						<h3 class="h6 mb-0"><a class="d-block" data-bs-toggle="collapse" href="#collapsecheque" role="button" aria-expanded="false" aria-controls="collapsecheque">Cheque Payment</a></h3>

						<div class="collapse" id="collapsecheque">
						<div class="py-2">
							<p class="mb-0">Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order won’t be shipped until the funds have cleared in our account.</p>
						</div>
						</div>
					</div>

					<div class="border p-3 mb-5">
						<h3 class="h6 mb-0"><a class="d-block" data-bs-toggle="collapse" href="#collapsepaypal" role="button" aria-expanded="false" aria-controls="collapsepaypal">Paypal</a></h3>

						<div class="collapse" id="collapsepaypal">
						<div class="py-2">
							<p class="mb-0">Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order won’t be shipped until the funds have cleared in our account.</p>
						</div>
						</div>
					</div>

					<div class="form-group">
						<button class="btn btn-black btn-lg py-3 btn-block" onclick="window.location='thankyou.html'">Place Order</button>
					</div>

					</div>
				</div>
				</div>

			</div>
			</div>
			<!-- </form> -->
		</div>
		</div>
{% endblock content %}

{% block scripts %}
		{{ block.super}}
		<script type="text/javascript">
			$(document).ready(function() {
				"use strict";
				const cartItems = shoppingCart.listItemInCart();
				console.log(cartItems);
				const cartTotal = shoppingCart.getTotalCartCost();
				let output = "";
				for (let i in cartItems) {
					const item = cartItems[i];
					const itemTotalCost = shoppingCart.getItemTotalCost(i);
					output += "<tr>";
					output += "<td>" + item.name + ' <strong class="mx-2">x</strong> '+ item.count + '</td>'
					output += '<td>' + itemTotalCost + '</td>'
					output += "</tr>"; 
				}
				output += '<tr>'
				output += '<td class="text-black font-weight-bold"><strong>Cart Subtotal</strong></td>'
				output += '<td class="text-black">' + cartTotal + '</td>';
				output += '</tr>'
				output += '<tr>'
				output += '<td class="text-black font-weight-bold"><strong>Order Total</strong></td>'
				output += '<td class="text-black">' + cartTotal + '</td>';
				output += '</tr>'
				$("#orderTable tbody").html(output);
			})
		</script>
{% endblock scripts %}

products/templates/products/navbar.html
{% load static %}
<!-- Start Header/Navigation -->
<nav class="custom-navbar navbar navbar navbar-expand-md navbar-dark bg-dark" arial-label="Furni navigation bar">

    <div class="container">
        <a class="navbar-brand" href="index.html">Furni<span>.</span></a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsFurni" aria-controls="navbarsFurni" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsFurni">
            <ul class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0">
                <!-- <li class="nav-item ">
                    <a class="nav-link" href="index.html">Home</a>
                </li> -->
                <li class="active"><a class="nav-link" href="{% url 'products:list' %}">Shop</a></li>
                <!-- <li><a class="nav-link" href="about.html">About us</a></li>
                <li><a class="nav-link" href="services.html">Services</a></li>
                <li><a class="nav-link" href="blog.html">Blog</a></li>
                <li><a class="nav-link" href="contact.html">Contact us</a></li> -->
            </ul>

            <ul class="custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5">
                {% if user.is_authenticated %}
                    <li><a class="nav-link" href="{% url 'profile' %}">Profile</a></li>
                    <li><a class="nav-link" href="{% url 'logout' %}"><img src="{% static 'products/images/logout.svg' %}"></a></li>
                {% else %}
                    <li><a class="nav-link" href="{% url 'login' %}"><img src="{% static 'products/images/user.svg' %}"></a></li>
                {% endif %}
                <li><a class="nav-link" href="{% url 'carts:list' %}"><img class="me-1" src="{% static 'products/images/cart.svg' %}"><span id="cart-item-count">0</span></a></li>
            </ul>
        </div>
    </div>
        
</nav>

products/templates/products/product_detail.html
{% extends "products/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
{% if product %}
    <ul>
        <li>{{ product.name }}</li>
        <li>{{ product.description }}</li>
        <li>{{ product.price }}</li>
        <li>{{ product.id }}</li>
    </ul>
{% endif %}
{% endblock content %}

products/templates/products/product_list.html
{% extends "products/base.html" %}
{% load static %}
{% block content %}
<div class="untree_co-section product-section before-footer-section">
	<div class="container">
		<div class="row">
			{% for product in product_list %}
				<div class="col-12 col-md-4 col-lg-3 mb-5">
					<div class="product-item">
						<a href="{% url 'products:detail' product.id %}">
							<img src="{{ product.image.url }}" class="img-fluid product-thumbnail">
							<h3 class="product-title">{{ product.name }}</h3>
							<strong class="product-price">{{ product.price }}</strong>
						</a>
						<span class="icon-cross add-to-cart" data-id="{{ product.id }}" data-name="{{ product.name }}" data-price="{{ product.price }}">
							<a>
								<img src="{%static 'products/images/cross.svg' %}" class="img-fluid">
							</a>
						</span>
                        <p>{{product.user}}</p>
					</div>
				</div> 
			{% endfor %}
		</div>
	</div>
</div>

{% endblock content %}

{% block scripts %}
	{% comment %} gather all the scripts from parent html (base.html) {% endcomment %}
	{% comment %} reference:
	https://stackoverflow.com/questions/31202918/django-jquery-handling-template-inheritence-and-js-files-loading {% endcomment %}
	{{ block.super }}
	<script type="text/javascript">
		$(document).ready(function() {
			"use strict";
			$(".add-to-cart").on('click', function(event) {
				const itemId = $(this).data("id");
				const itemName = $(this).data("name");
				const itemPrice = $(this).data("price");
				shoppingCart.addItemToCart(itemId, itemName, itemPrice, 1);
				let itemsInCart = shoppingCart.listItemInCart();
				console.log("itemsInCart: ", itemsInCart);
				console.log("cartCount: ", shoppingCart.getCartCount());

				console.log("triggering new event ", shoppingCart.getCartCount())
        		$(document).trigger('UpdateTotalCountEvent', shoppingCart.getCartCount())

			});

		});
	</script>
{% endblock scripts %}

users/templates/users/profile.html
{% extends "products/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <h1>Profile user name: {{ user.username }}</h1>
    </div>
{% endblock content %}